service: image-tools

provider:
  name: aws
  runtime: rust
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  memorySize: 256
  timeout: 10
  versionFunctions: false
  logRetentionInDays: 1

plugins:
  - serverless-rust

package:
  individually: true

functions:
  imageResizeFunction:
    handler: image_resize
    events:
      - httpApi:
          method: POST
          path: /image/resize
          payload: '2.0'
